from flask import Flask, render_template, request, jsonify
from transformers import AutoModelForCausalLM, AutoTokenizer 
import torch

# Load the PCOS dataset or information here
# For example, you can load a list of questions related to PCOS and their corresponding answers

import pcos_data


tokenizer = AutoTokenizer.from_pretrained("microsoft/DialoGPT-medium")
model = AutoModelForCausalLM.from_pretrained("microsoft/DialoGPT-medium")

app = Flask(__name__)

keyword_responses = {
    "medications": "There are various medications used to manage PCOS symptoms and improve fertility in some cases. Common medications include birth control pills to regulate menstrual cycles and reduce androgen levels, metformin to improve insulin sensitivity and regulate ovulation, and anti-androgen medications to address symptoms like acne and excessive hair growth.<br> Additionally, fertility medications such as clomiphene citrate or letrozole may be prescribed to induce ovulation in individuals trying to conceive. It's essential to consult with a healthcare professional to determine the most suitable treatment plan based on individual needs and health goals.",
    "causes": "The exact cause of PCOS is not fully understood, but it is believed to involve a combination of genetic and environmental factors.<br> Insulin resistance, which affects how the body processes glucose, plays a significant role in PCOS development. Hormonal imbalances, such as elevated levels of androgens and irregularities in gonadotropin-releasing hormone (GnRH) secretion, also contribute to PCOS.",
    "symptoms": "The most common signs and symptoms of PCOS include:<br><b>1.Irregular periods:</b> Abnormal menstruation involves missing periods or not having a period at all. It may also involve heavy bleeding during periods.<br><b>2.Abnormal hair growth:</b> You may grow excess facial hair or experience heavy hair growth on your arms, chest and abdomen (hirsutism). This affects up to 70% of people with PCOS.<br><b>3.Acne: </b>PCOS can cause acne, especially on your back, chest and face. This acne may continue past your teenage years and may be difficult to treat.<br><b>4.Obesity:</b> Between 40% and 80% of people with PCOS have obesity and have trouble maintaining a weight that’s healthy for them.<br><b>5.Darkening of the skin:</b> You may get patches of dark skin, especially in the folds of your neck, armpits, groin (between the legs) and under your breasts. This is known as acanthosis nigricans.<br><b>6.Cysts: </b>Many people with PCOS have ovaries that appear larger or with many follicles (egg sac cysts) on ultrasound.<br><b>7.Skin tags:</b> Skin tags are little flaps of extra skin. They’re often found in your armpits or on your neck.<br><b>8.Thinning hair: </b>People with PCOS may lose patches of hair on their head or start to bald.<br><b>9.Infertility:</b> PCOS is the most common cause of infertility in people AFAB. Not ovulating regularly or frequently can result in not being able to conceive.",
    "diet": "A well-balanced diet plays a crucial role in managing PCOS symptoms and promoting overall health.<br> For individuals with PCOS, focusing on nutrient-dense foods and making mindful choices can help improve insulin sensitivity, regulate menstrual cycles, and support weight management goals.<br> A PCOS-friendly diet typically includes plenty of fruits, vegetables, whole grains, lean proteins, and healthy fats while minimizing intake of processed foods, sugary snacks, and refined carbohydrates.<br> Emphasizing complex carbohydrates with a low glycemic index, such as whole grains, legumes, and non-starchy vegetables, can help stabilize blood sugar levels and reduce insulin resistance.<br> Incorporating protein-rich foods like lean meats, fish, eggs, tofu, and legumes into meals and snacks can help promote satiety and regulate appetite.<br> Additionally, including sources of healthy fats such as avocados, nuts, seeds, and olive oil can support hormonal balance and overall well-being in individuals with PCOS.<b>It's essential for individuals with PCOS to work closely with their healthcare providers to develop a comprehensive treatment plan tailored to their unique needs and goals.<b>",
    "treatment": "Treating PCOS often involves a multidisciplinary approach with input from various healthcare professionals, including endocrinologists, gynecologists, dietitians, and sometimes psychologists.<br> Lifestyle modifications, such as maintaining a healthy weight, following a balanced diet low in refined carbohydrates, and engaging in regular physical activity, are key components of managing PCOS.<br> In addition to lifestyle changes, medications such as metformin, spironolactone, and hormonal contraceptives may be prescribed to address specific symptoms like insulin resistance, acne, and irregular menstrual cycles.<br> For women trying to conceive, fertility treatments such as ovulation induction with medications or assisted reproductive technologies like in vitro fertilization (IVF) may be recommended.<br> <b>It's essential for individuals with PCOS to work closely with their healthcare providers to develop a comprehensive treatment plan tailored to their unique needs and goals.<b>",
    "thank you": "You're welcome!🌟 If you have any more questions, feel free to ask.",
    "bye": "Goodbye! Feel free to reach out if you have any more questions or need assistance in the future. Take care!",
    "reduce pcos": "Reducing PCOS (Polycystic Ovary Syndrome) entirely may not be possible as its exact cause is not fully understood and it can involve a combination of genetic, hormonal, and environmental factors.<br> However, there are steps you can take to reduce your risk of developing PCOS or to manage its symptoms effectively:<br> 1. Maintain a Healthy Weight: Being overweight or obese is associated with an increased risk of PCOS and can worsen its symptoms. Aim for a balanced diet rich in fruits, vegetables, whole grains, and lean proteins, and engage in regular physical activity to help manage your weight.<br> 2. Balanced Diet: Focus on a diet that includes a variety of nutrient-rich foods, such as fruits, vegetables, whole grains, lean proteins, and healthy fats. Limit the intake of processed foods, sugary snacks, and drinks, as well as foods high in saturated and trans fats.<br> 3. Regular Exercise: Engage in regular physical activity to help improve insulin sensitivity, manage weight, and reduce stress. Aim for at least 150 minutes of moderate-intensity aerobic activity or 75 minutes of vigorous-intensity activity per week, along with muscle-strengthening exercises on two or more days per week.<br> 4. Manage Stress: Chronic stress can worsen hormonal imbalances and exacerbate PCOS symptoms. Practice stress-reducing techniques such as mindfulness meditation, deep breathing exercises, yoga, or spending time in nature to promote relaxation and well-being.<br> 5. Limit Alcohol and Quit Smoking: Excessive alcohol consumption and smoking can disrupt hormonal balance and exacerbate PCOS symptoms. Limit alcohol intake and avoid smoking to reduce your risk of developing PCOS or worsening its symptoms.<br> 6. Regular Health Check-ups: Attend regular medical check-ups and screenings to monitor your health status, including blood sugar levels, lipid profile, and hormonal balance. Early detection and management of any underlying health conditions can help prevent or mitigate the progression of PCOS-related complications.<br> 7. Consult with Healthcare Providers: If you suspect you may have PCOS or are experiencing symptoms such as irregular periods, acne, excessive hair growth, or weight gain, consult with healthcare providers for proper evaluation, diagnosis, and treatment. Early intervention and comprehensive management can help alleviate symptoms and improve overall health outcomes.<br> By adopting a healthy lifestyle, managing stress, and seeking appropriate medical care, you can take proactive steps to reduce your risk of developing PCOS and effectively manage its symptoms if diagnosed.",
    "treatment of pcos": "Treating PCOS often involves a multidisciplinary approach with input from various healthcare professionals, including endocrinologists, gynecologists, dietitians, and sometimes psychologists.<br> Lifestyle modifications, such as maintaining a healthy weight, following a balanced diet low in refined carbohydrates, and engaging in regular physical activity, are key components of managing PCOS.<br> In addition to lifestyle changes, medications such as metformin, spironolactone, and hormonal contraceptives may be prescribed to address specific symptoms like insulin resistance, acne, and irregular menstrual cycles.<br> For women trying to conceive, fertility treatments such as ovulation induction with medications or assisted reproductive technologies like in vitro fertilization (IVF) may be recommended.<br> <b>It's essential for individuals with PCOS to work closely with their healthcare providers to develop a comprehensive treatment plan tailored to their unique needs and goals.<b>",
    "managing pcos symptoms": "Managing PCOS symptoms often involves a combination of lifestyle modifications and medical interventions.<br> Lifestyle changes, including adopting a healthy diet, regular exercise, stress reduction techniques, and adequate sleep, can help improve insulin sensitivity, regulate menstrual cycles, and reduce the risk of complications associated with PCOS.<br> In addition to lifestyle modifications, various medications may be used to manage specific symptoms of PCOS.<br> For example, hormonal contraceptives can help regulate menstrual cycles and reduce excess hair growth and acne, while insulin-sensitizing drugs like metformin can improve insulin resistance and lower androgen levels.<br> Weight management strategies are also crucial, as even modest weight loss can lead to significant improvements in PCOS symptoms and overall health outcomes.",
    "remedies": "While lifestyle modifications and conventional medical treatments are the mainstay of PCOS management, some individuals may also explore natural remedies or complementary therapies to alleviate symptoms and improve overall well-being.<br> These may include dietary supplements such as inositol, omega-3 fatty acids, and vitamin D, which have shown promise in improving insulin sensitivity and menstrual regularity in women with PCOS.<br> Herbal remedies like spearmint tea or supplements containing ingredients like saw palmetto or chasteberry are sometimes used to address symptoms like hirsutism and menstrual irregularities, although evidence supporting their efficacy is limited.<br><b> It's essential to consult with a healthcare provider before trying any natural remedies, as they may interact with medications or have adverse effects, especially in certain populations such as pregnant or breastfeeding individuals.<b>",
    "prevent pcos": "Reducing PCOS (Polycystic Ovary Syndrome) entirely may not be possible as its exact cause is not fully understood and it can involve a combination of genetic, hormonal, and environmental factors.<br> However, there are steps you can take to reduce your risk of developing PCOS or to manage its symptoms effectively:<br> 1. Maintain a Healthy Weight: Being overweight or obese is associated with an increased risk of PCOS and can worsen its symptoms. Aim for a balanced diet rich in fruits, vegetables, whole grains, and lean proteins, and engage in regular physical activity to help manage your weight.<br> 2. Balanced Diet: Focus on a diet that includes a variety of nutrient-rich foods, such as fruits, vegetables, whole grains, lean proteins, and healthy fats. Limit the intake of processed foods, sugary snacks, and drinks, as well as foods high in saturated and trans fats.<br> 3. Regular Exercise: Engage in regular physical activity to help improve insulin sensitivity, manage weight, and reduce stress. Aim for at least 150 minutes of moderate-intensity aerobic activity or 75 minutes of vigorous-intensity activity per week, along with muscle-strengthening exercises on two or more days per week.<br> 4. Manage Stress: Chronic stress can worsen hormonal imbalances and exacerbate PCOS symptoms. Practice stress-reducing techniques such as mindfulness meditation, deep breathing exercises, yoga, or spending time in nature to promote relaxation and well-being.<br> 5. Limit Alcohol and Quit Smoking: Excessive alcohol consumption and smoking can disrupt hormonal balance and exacerbate PCOS symptoms. Limit alcohol intake and avoid smoking to reduce your risk of developing PCOS or worsening its symptoms.<br> 6. Regular Health Check-ups: Attend regular medical check-ups and screenings to monitor your health status, including blood sugar levels, lipid profile, and hormonal balance. Early detection and management of any underlying health conditions can help prevent or mitigate the progression of PCOS-related complications.<br> 7. Consult with Healthcare Providers: If you suspect you may have PCOS or are experiencing symptoms such as irregular periods, acne, excessive hair growth, or weight gain, consult with healthcare providers for proper evaluation, diagnosis, and treatment. Early intervention and comprehensive management can help alleviate symptoms and improve overall health outcomes.<br> By adopting a healthy lifestyle, managing stress, and seeking appropriate medical care, you can take proactive steps to reduce your risk of developing PCOS and effectively manage its symptoms if diagnosed.",
    "pcos": "PCOS, or Polycystic Ovary Syndrome, is a hormonal disorder that affects people with ovaries.<br> It's characterized by irregular periods, excess androgen levels, and polycystic ovaries.<br> People with PCOS may face challenges with fertility and have an increased risk of developing other health issues like diabetes and heart disease."
}

@app.route("/")
def index():
    return render_template('chat.html')

@app.route("/get", methods=["POST"])
def chat():
    msg = request.form["msg"]
    return get_chat_response(msg)

def get_chat_response(text):
    # Check if the user input is a question related to PCOS
    if text.lower() in pcos_data.pcos_data:
        return pcos_data.pcos_data[text.lower()]
    else:
        # Check if the message contains any keywords
        for keyword, response in keyword_responses.items():
            if keyword in text.lower():
                return response
    
    # If not a keyword or related to PCOS, use the chatbot model to generate a response
    return generate_response(text)


def generate_response(text):
    # Let's chat for 5 lines
    for step in range(5):
        # Encode the new user input, add the eos_token and return a tensor in Pytorch
        new_user_input_ids = tokenizer.encode(str(text) + tokenizer.eos_token, return_tensors='pt')
    
        # Append the new user input tokens to the chat history
        bot_input_ids = torch.cat([chat_history_ids, new_user_input_ids], dim=-1) if step > 0 else new_user_input_ids
    
        # Generated a response while limiting the total chat history to 1000 tokens
        chat_history_ids = model.generate(bot_input_ids, max_length=1000, pad_token_id=tokenizer.eos_token_id)
    
        # Pretty print last output tokens from bot
        return tokenizer.decode(chat_history_ids[:, bot_input_ids.shape[-1]:][0], skip_special_tokens=True)

if __name__ == '__main__':
    app.run()
